services:
  todo-app:
    image: todo-app
    ports:
      - 9090:9090
    environment:
      - DB_PASSWORD=Raznie71593)
      - DB_USER=postgres
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./.database/postgres/data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Raznie71593)
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5