name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Go 1.22
        uses: actions/setup-go@v3 # Use the latest version
        with:
          go-version: 1.22

      - name: Test
        run: go test ./...

  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test
    services:
      docker:
        image: docker:latest # Use containerd
        options: '--privileged --network host --pid host'
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max